name: Generate Snake

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Generate Snake
        id: snake-gif
        run: |
          github_user_name="${{ github.repository_owner }}"
          gif_out_path="./assets/github-contribution-grid-snake.gif"
          svg_out_path="./assets/github-contribution-grid-snake.svg"
          echo "github_user_name=$github_user_name" >> $GITHUB_ENV
          echo "gif_out_path=$gif_out_path" >> $GITHUB_ENV
          echo "svg_out_path=$svg_out_path" >> $GITHUB_ENV
          npx snk
          # 如果你的存储库包含了 Platane/snk，你可以使用下面的命令：
          # npx @platane/snk

      - name: Push to GitHub
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add ./assets/github-contribution-grid-snake.gif ./assets/github-contribution-grid-snake.svg
          git commit -m 'Generate Contribution Snake'
          git push origin main
