name: Update events

on:
  watch:
    types: started
  schedule:
    - cron:  '* * * * *'

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - name: Social Readme
        uses: zylele/social-readme@master
        with:
          blog_rss_link: https://sxlz.me/atom.xml
          blog_limit: 10
          douban_name: sxlz888
          douban_limit: 10